### ISSUE TITLE
ltp leafref

### ISSUE THREAD

**Issue by younglee-ietf** [younglee-ietf/actn#1]
can you check if this is correct: (somehow the tree does not specify the path info for ltp and connectivity-matrix-id)

leaf ltp {
            type leafref {
               path "/nw:networks/nw:network/nw:node/"
	           +"nt:termination-point/tet:te-tp-id";
            }
            description
                "Reference LTP in the TE-topology";
Also:
leaf connectivity-matrix-id{
            type leafref {
                path "/nw:networks/nw:network/nw:node/tet:te/"
                + "tet:te-node-attributes/"
                + "tet:connectivity-matrices/"
                + "tet:connectivity-matrix/tet:id";
            }
            description
                "reference to connectivity-matrix";
        }

**Comment by younglee-ietf** [comment]
fixed.

**Comment by dhruvdhody** [comment]
is this the issue because the path is too big and tree only show leafref?
