### ISSUE TITLE
AP definition clarification

### ISSUE THREAD

**Issue by sunseawq** [younglee-ietf/actn#4]
I think AP definition in VN model should be clarified or refined, since I believe An AP is a logical identifier shared between the customer and the operator used to identify not only an access link but also a network attachment point or an endpoint. This can be proved by some of text described in the draft,e g..,
"Characteristics of Access Points (APs) that describe customer's end point characteristics; ".
Another example is
"
   If we were to create a VN where we have four VN-members as follows:

                  VN-Member 1       L1-L4
                  VN-Member 2       L1-L7
                  VN-Member 3       L2-L4
                  VN-Member 4       L3-L8

          Where L1, L2, L3, L4, L7 and L8 correspond to a Customer
          End-Point, respectively.
"
I think we should make text consistent in the document.

**Comment by younglee-ietf** [comment]
Can you suggest where to put the suggested text in the draft and give the exact text you'd like to add in the draft? Thanks.

**Comment by dhruvdhody** [comment]
See https://tools.ietf.org/html/draft-ietf-teas-actn-vn-yang-07#section-3.2.1
